name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-environment: [flake8, tests]
        python-version: [3.7]
    steps:
    - name: Upgrade Git
      run: apt-get update && apt-get install -y git
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run ${{ matrix.tox-environment }}
      run: tox -e ${{ matrix.tox-environment }}
    - name: Send coverage to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install coveralls
        coveralls
